// SPDX-License-Identifier: MIT

pragma solidity ^0.8.24;

import { IIdentityManager } from "./interfaces/IIdentityManager.sol";

/**
 * @title Identity Manager Contract
 * @notice Manages voter identity verification and ID generation
 * @dev Inherits from IIdentityManager interface
 */
contract IdentityManager is IIdentityManager {
    /// @dev Array of addresses that are allowed to vote
    address[] private _allowedVoters;

    /// @notice Contract constructor
    /// @param allowedVoters Array of addresses that will be allowed to vote
    constructor(address[] memory allowedVoters) {
        _allowedVoters = allowedVoters;
    }

    /// @notice Verifies if sender is allowed to vote and generates their voter ID
    /// @dev Voter ID is generated by hashing the sender's address
    /// @return bytes32 Hash of the sender's address as their voter ID
    function verifyProofAndGetVoterId() public view returns (bytes32) {
        // Convert sender address to bytes32 hash for security
        bytes32 voterId = keccak256(abi.encodePacked(msg.sender));

        // Verify sender is in allowed voters list
        bool isAllowed = false;
        for (uint256 i = 0; i < _allowedVoters.length; i++) {
            if (_allowedVoters[i] == msg.sender) {
                isAllowed = true;
                break;
            }
        }

        if (!isAllowed) revert NotAllowed();

        return voterId;
    }
}
